import { Meals } from './meals';

export const MEALS: Meals[] = [
    {
        id: 1,
        title: 'Greek Yogurt',
        type:'Breakfast',
        image: '/assets/meals2.png',
        ing: 'Greek yogurt',
        ing2: 'Banana',
        ing3: 'Nuts',
        ing4: 'Blueberries',
        por: '100 g',
        por2: '1/2',
        por3: '15 g',
        por4: '10 g',
    },
    {
        id: 2,
        title: 'Chicken Wrap',
        type:'Lunch',
        image: '/assets/meals3.png',
        ing: 'Chicken Breast',
        ing2: 'Cheese',
        ing3: 'Bacon',
        ing4: 'Tomato',
        por: '1',
        por2: '3tsp',
        por3: '3 slices',
        por4: '1/2 sliced',
    },
    {
        id: 3,
        title: 'Roasted Salmon',
        type:'Dinner',
        image: '/assets/meals1.png',
        ing: 'Salmon Filet',
        ing2: 'Asparagus',
        ing3: 'Cherry Tomatoes',
        ing4: 'Lemon',
        por: '2 lbs',
        por2: '4 bunches',
        por3: '1',
        por4: '3 slices',
    },
]